[[plugins]]
repo = 'Shougo/dein.vim'

# =============
# ==  color  ==
# =============
repo = 'cocopon/iceberg.vim'
hook_add = 'colorscheme iceberg'

[[plugins]]
repo = 'flazz/vim-colorschemes'
# hook_add = 'colorscheme jellybeans'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  map <C-e> :NERDTreeToggle<CR>
  let g:NERDTreeShowHidden=1
'''

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  set signcolumn=yes
  set updatetime=100
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
  let g:winresizer_start_key = '<C-T>'
'''

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
