[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'map <C-e> :NERDTreeToggle<CR>'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'flazz/vim-colorschemes'
hook_add = 'colorscheme jellybeans'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
  let g:winresizer_start_key = '<C-T>'
'''
