[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
on_path = '.*'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'tpope/vim-endwise'
on_i = 1

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['rb']

[[plugins]]
repo  = 'tpope/vim-rails'
on_ft = ['rb']

[[plugins]]
repo = 'joonty/vdebug.git'
on_ft = ['php']
