[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['md']

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['md']

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'tpope/vim-endwise'
on_i = 1

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

# =============
# ==  ruby   ==
# =============

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['rb']

[[plugins]]
repo  = 'tpope/vim-rails'
on_ft = ['rb']

# =============
# ==   php   ==
# =============

[[plugins]]
repo = 'joonty/vdebug.git'
on_ft = ['php']

# =============
# ==   js    ==
# =============

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript']

# =============
# ==  html   ==
# =============

[[plugins]]
repo = 'gregsexton/MatchTag'
on_path = '.*'

# ==============
# ==  golang  ==
# ==============

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
  let g:go_highlight_functions = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_structs = 1
  let g:go_fmt_command = "goimports"
'''
